"""perfis super_admin gestor solicitacoes_senha tema barbearia

Revision ID: 1d48f9d7cda0
Revises: e2f4149e08ac
Create Date: 2026-05-29 11:51:07.447581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d48f9d7cda0'
down_revision = 'e2f4149e08ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitacoes_senha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('barbearias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cor_primaria', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('cor_fundo', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('cor_card', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('logo_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('fonte', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbearias', schema=None) as batch_op:
        batch_op.drop_column('fonte')
        batch_op.drop_column('logo_url')
        batch_op.drop_column('cor_card')
        batch_op.drop_column('cor_fundo')
        batch_op.drop_column('cor_primaria')

    op.drop_table('solicitacoes_senha')
    # ### end Alembic commands ###
