"""v2 planos vip features customizacao e campos cliente

Revision ID: 226f742c7c4d
Revises: e5f6a1b2c3d4
Create Date: 2026-06-20 13:24:36.547519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226f742c7c4d'
down_revision = 'e5f6a1b2c3d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barbearia_customizacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.Column('cor_primaria', sa.String(length=7), nullable=False, server_default='#BA7517'),
    sa.Column('cor_secundaria', sa.String(length=7), nullable=False, server_default='#1a1a1a'),
    sa.Column('cor_acentuacao', sa.String(length=7), nullable=False, server_default='#FFD700'),
    sa.Column('texto_primario', sa.String(length=7), nullable=False, server_default='#FFFFFF'),
    sa.Column('texto_secundario', sa.String(length=7), nullable=False, server_default='#CCCCCC'),
    sa.Column('texto_terciario', sa.String(length=7), nullable=False, server_default='#888888'),
    sa.Column('botao_primario', sa.String(length=7), nullable=False, server_default='#FFD700'),
    sa.Column('botao_secundario', sa.String(length=7), nullable=False, server_default='#555555'),
    sa.Column('logo_filename', sa.String(length=255), nullable=True),
    sa.Column('fundo_padrao_filename', sa.String(length=255), nullable=True),
    sa.Column('fonte', sa.String(length=50), nullable=False, server_default='Inter'),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barbearia_id')
    )
    op.create_table('feature_barbearia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.Column('planos', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('relatorios_avancados', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('vip_brindes', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('agendamento_login', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('historico_cliente', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('cupons', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('fila_espera', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('comissao', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('notificacoes', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('pix_integrado', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barbearia_id')
    )
    op.create_table('vip_niveis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('brinde_descricao', sa.Text(), nullable=False),
    sa.Column('tipo_brinde', sa.String(length=20), nullable=False),
    sa.Column('valor_desconto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False, server_default='true'),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barbearia_id', 'nivel', name='uq_barbearia_nivel')
    )
    op.create_table('cliente_vip',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.Column('nivel_vip_atual', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('brindes_resgatados', sa.Text(), nullable=True),
    sa.Column('data_proxima_renovacao', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'barbearia_id', name='uq_cliente_barbearia_vip')
    )
    op.create_table('planos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.Column('barbeiro_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco_mensal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False, server_default='true'),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['barbeiro_id'], ['barbeiros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente_plano',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.Column('barbeiro_id', sa.Integer(), nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False, server_default='true'),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['barbeiro_id'], ['barbeiros.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['plano_id'], ['planos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente_plano_solicitacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.Column('barbeiro_id', sa.Integer(), nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('comprovante_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('aprovado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['barbeiro_id'], ['barbeiros.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['plano_id'], ['planos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plano_servicos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('limite_uso_mensal', sa.Integer(), nullable=False),
    sa.Column('dias_expiracao', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False, server_default='true'),
    sa.ForeignKeyConstraint(['plano_id'], ['planos.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plano_id', 'servico_id', name='uq_plano_servico')
    )
    op.create_table('cliente_plano_uso',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_plano_id', sa.Integer(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('data_uso', sa.Date(), nullable=False),
    sa.Column('semana_do_mes', sa.Integer(), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False, server_default='false'),
    sa.ForeignKeyConstraint(['cliente_plano_id'], ['cliente_plano.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('barbearias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chave_pix', sa.String(length=255), nullable=True))

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ultimo_acesso', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('primeira_visita', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('primeira_visita')
        batch_op.drop_column('ultimo_acesso')
        batch_op.drop_column('senha_hash')

    with op.batch_alter_table('barbearias', schema=None) as batch_op:
        batch_op.drop_column('chave_pix')

    op.drop_table('cliente_plano_uso')
    op.drop_table('plano_servicos')
    op.drop_table('cliente_plano_solicitacao')
    op.drop_table('cliente_plano')
    op.drop_table('planos')
    op.drop_table('cliente_vip')
    op.drop_table('vip_niveis')
    op.drop_table('feature_barbearia')
    op.drop_table('barbearia_customizacao')
    # ### end Alembic commands ###
    