"""foto clientes produtos observacoes telefone unico

Revision ID: 6e96ea191abc
Revises: 9129864563c8
Create Date: 2026-05-28 22:15:36.885842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e96ea191abc'
down_revision = '9129864563c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(None, ['telefone'])

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('foto')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('observacoes')
        batch_op.drop_column('foto')

    # ### end Alembic commands ###
