"""multi_tenant_barbearia_id

Revision ID: e2f4149e08ac
Revises: 6e96ea191abc
Create Date: 2026-05-28 23:32:46.284036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f4149e08ac'
down_revision = '6e96ea191abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barbearias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barbearia_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'barbearias', ['barbearia_id'], ['id'])

    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barbearia_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'barbearias', ['barbearia_id'], ['id'])

    with op.batch_alter_table('barbeiros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barbearia_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'barbearias', ['barbearia_id'], ['id'])

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barbearia_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('clientes_telefone_key'), type_='unique')
        batch_op.create_unique_constraint('uq_cliente_barbearia_telefone', ['barbearia_id', 'telefone'])
        batch_op.create_foreign_key(None, 'barbearias', ['barbearia_id'], ['id'])

    with op.batch_alter_table('configuracao_agenda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barbearia_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'barbearias', ['barbearia_id'], ['id'])

    with op.batch_alter_table('horarios_bloqueados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barbearia_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'barbearias', ['barbearia_id'], ['id'])

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barbearia_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'barbearias', ['barbearia_id'], ['id'])

    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barbearia_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'barbearias', ['barbearia_id'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barbearia_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'barbearias', ['barbearia_id'], ['id'])

    # ── PARTE 3: Migração de dados — barbearia inicial ────────────────────────
    op.execute("""
        INSERT INTO barbearias (nome, slug, ativo, criado_em)
        VALUES ('Caio César Barbearia', 'caio', TRUE, NOW())
    """)
    op.execute("""
        UPDATE usuarios          SET barbearia_id = (SELECT id FROM barbearias WHERE slug = 'caio');
        UPDATE barbeiros         SET barbearia_id = (SELECT id FROM barbearias WHERE slug = 'caio');
        UPDATE clientes          SET barbearia_id = (SELECT id FROM barbearias WHERE slug = 'caio');
        UPDATE servicos          SET barbearia_id = (SELECT id FROM barbearias WHERE slug = 'caio');
        UPDATE produtos          SET barbearia_id = (SELECT id FROM barbearias WHERE slug = 'caio');
        UPDATE agendamentos      SET barbearia_id = (SELECT id FROM barbearias WHERE slug = 'caio');
        UPDATE atendimentos      SET barbearia_id = (SELECT id FROM barbearias WHERE slug = 'caio');
        UPDATE configuracao_agenda SET barbearia_id = (SELECT id FROM barbearias WHERE slug = 'caio');
        UPDATE horarios_bloqueados SET barbearia_id = (SELECT id FROM barbearias WHERE slug = 'caio');
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('barbearia_id')

    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('barbearia_id')

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('barbearia_id')

    with op.batch_alter_table('horarios_bloqueados', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('barbearia_id')

    with op.batch_alter_table('configuracao_agenda', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('barbearia_id')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_cliente_barbearia_telefone', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('clientes_telefone_key'), ['telefone'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('barbearia_id')

    with op.batch_alter_table('barbeiros', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('barbearia_id')

    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('barbearia_id')

    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('barbearia_id')

    op.drop_table('barbearias')
    # ### end Alembic commands ###
